"use client";

// Experiment 06: GPU curl-noise flow field.
//
// 15,000 bone-colored points drifting through a 2D curl-noise vector field.
// "Curl noise" is divergence-free flow generated by rotating the gradient
// of a scalar noise field by 90°. The result feels like fluid motion or
// wind: particles swirl around invisible eddies, weave through "current"
// lines, never blob into single dense clusters (because curl is
// divergence-free).
//
// Stateless implementation: every frame the vertex shader recomputes each
// particle's position from (seed position + time) → curl(noise) → drift.
// No physics state. No CPU loop. The cost is whatever the GPU spends on
// noise evaluation, which is trivial at 15k points (4 simplex calls per
// particle per frame).
//
// Stack:
//   - R3F orthographic Canvas (1 unit = 1 CSS pixel, origin centered)
//   - Classic ShaderMaterial with inline GLSL (Stefan Gustavson's snoise2d
//     and a curl wrapper). Same path as Experiments 01–05.
//   - Additive blending so overlapping particles brighten naturally.
//   - Bloom on the bright clusters.

import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { Bloom, EffectComposer } from "@react-three/postprocessing";
import { useEffect, useMemo, useRef } from "react";
import * as THREE from "three";

const PARTICLE_COUNT = 15000;
const SEED_HALF_WIDTH = 1100; // x range for initial seed positions
const SEED_HALF_HEIGHT = 700; // y range for initial seed positions

const NOISE_SCALE = 0.0028;   // smaller = larger flow features
const FLOW_SPEED = 0.14;       // how fast time advances through the noise field
const FLOW_AMPLITUDE = 220;    // max drift distance from seed in pixels

const POINT_SIZE_PX = 1.6;
const POINT_COLOR = 0xf5f2ec; // bone
const POINT_ALPHA = 0.55;
const BG_COLOR = "#0A0A0B";

const vertexShader = /* glsl */ `
  uniform float uPointSize;
  uniform float uTime;
  uniform float uNoiseScale;
  uniform float uFlowSpeed;
  uniform float uFlowAmplitude;

  attribute float iSeedT;

  // Stefan Gustavson's 2D simplex noise (canonical implementation).
  vec3 permute(vec3 x) { return mod(((x * 34.0) + 1.0) * x, 289.0); }
  float snoise(vec2 v) {
    const vec4 C = vec4(0.211324865405187, 0.366025403784439,
                       -0.577350269189626, 0.024390243902439);
    vec2 i  = floor(v + dot(v, C.yy));
    vec2 x0 = v - i + dot(i, C.xx);
    vec2 i1 = (x0.x > x0.y) ? vec2(1.0, 0.0) : vec2(0.0, 1.0);
    vec4 x12 = x0.xyxy + C.xxzz;
    x12.xy -= i1;
    i = mod(i, 289.0);
    vec3 p = permute(permute(i.y + vec3(0.0, i1.y, 1.0))
                     + i.x + vec3(0.0, i1.x, 1.0));
    vec3 m = max(0.5 - vec3(dot(x0, x0),
                            dot(x12.xy, x12.xy),
                            dot(x12.zw, x12.zw)), 0.0);
    m = m * m; m = m * m;
    vec3 x = 2.0 * fract(p * C.www) - 1.0;
    vec3 h = abs(x) - 0.5;
    vec3 ox = floor(x + 0.5);
    vec3 a0 = x - ox;
    m *= 1.79284291400159 - 0.85373472095314 * (a0 * a0 + h * h);
    vec3 g;
    g.x  = a0.x  * x0.x  + h.x  * x0.y;
    g.yz = a0.yz * x12.xz + h.yz * x12.yw;
    return 130.0 * dot(m, g);
  }

  // 2D curl: rotate the noise gradient 90° → divergence-free vector field.
  // This is the cheap-but-clean way to get fluid-style flow on 2D.
  vec2 curl2D(vec2 p) {
    const float eps = 0.01;
    float nxp = snoise(p + vec2(eps, 0.0));
    float nxn = snoise(p - vec2(eps, 0.0));
    float nyp = snoise(p + vec2(0.0, eps));
    float nyn = snoise(p - vec2(0.0, eps));
    float dx = (nxp - nxn) / (2.0 * eps);
    float dy = (nyp - nyn) / (2.0 * eps);
    return vec2(-dy, dx);
  }

  void main() {
    // Drive the noise input by (seed * scale) + animated time offset. The
    // per-particle iSeedT shifts each particle's phase so they don't all
    // pulse in unison.
    vec2 seed = position.xy;
    vec2 noiseInput = seed * uNoiseScale
                    + vec2(uTime * uFlowSpeed, 0.0)
                    + vec2(iSeedT * 6.2831);
    vec2 flow = curl2D(noiseInput);
    vec2 finalPos = seed + flow * uFlowAmplitude;

    vec4 mvPosition = modelViewMatrix * vec4(finalPos, 0.0, 1.0);
    gl_PointSize = uPointSize;
    gl_Position = projectionMatrix * mvPosition;
  }
`;

const fragmentShader = /* glsl */ `
  uniform vec3 uColor;
  uniform float uAlpha;
  void main() {
    vec2 coord = gl_PointCoord - vec2(0.5);
    float d = length(coord);
    if (d > 0.5) discard;
    float a = smoothstep(0.5, 0.4, d) * uAlpha;
    gl_FragColor = vec4(uColor, a);
  }
`;

function ScreenPixelCamera() {
  const { size, camera } = useThree();
  useEffect(() => {
    if (camera instanceof THREE.OrthographicCamera) {
      camera.left = -size.width / 2;
      camera.right = size.width / 2;
      camera.top = size.height / 2;
      camera.bottom = -size.height / 2;
      camera.updateProjectionMatrix();
    }
  }, [camera, size]);
  return null;
}

function CurlField() {
  // Generate seed positions and per-particle time offsets once at mount.
  const { positions, seedTimes } = useMemo(() => {
    const positions = new Float32Array(PARTICLE_COUNT * 3);
    const seedTimes = new Float32Array(PARTICLE_COUNT);
    for (let i = 0; i < PARTICLE_COUNT; i++) {
      // Uniform rectangular distribution covers the typical viewport.
      positions[i * 3] = (Math.random() * 2 - 1) * SEED_HALF_WIDTH;
      positions[i * 3 + 1] = (Math.random() * 2 - 1) * SEED_HALF_HEIGHT;
      positions[i * 3 + 2] = 0;
      seedTimes[i] = Math.random();
    }
    return { positions, seedTimes };
  }, []);

  const material = useMemo(() => {
    const dpr = typeof window !== "undefined" ? window.devicePixelRatio || 1 : 1;
    return new THREE.ShaderMaterial({
      vertexShader,
      fragmentShader,
      uniforms: {
        uPointSize: { value: POINT_SIZE_PX * dpr },
        uTime: { value: 0 },
        uNoiseScale: { value: NOISE_SCALE },
        uFlowSpeed: { value: FLOW_SPEED },
        uFlowAmplitude: { value: FLOW_AMPLITUDE },
        uColor: { value: new THREE.Color(POINT_COLOR) },
        uAlpha: { value: POINT_ALPHA },
      },
      transparent: true,
      depthWrite: false,
      blending: THREE.AdditiveBlending,
    });
  }, []);

  const pointsRef = useRef<THREE.Points>(null);

  useFrame((state) => {
    material.uniforms.uTime.value = state.clock.elapsedTime;
  });

  return (
    <points ref={pointsRef} material={material}>
      <bufferGeometry>
        <bufferAttribute attach="attributes-position" args={[positions, 3]} />
        <bufferAttribute attach="attributes-iSeedT" args={[seedTimes, 1]} />
      </bufferGeometry>
    </points>
  );
}

export function CurlNoiseField({
  index,
  title,
  meta,
}: {
  index: string;
  title: string;
  meta: string;
}) {
  return (
    <section className="relative h-screen w-full overflow-hidden border-b border-bone/5 bg-ink">
      <Canvas
        orthographic
        camera={{ position: [0, 0, 10], near: 0.1, far: 100, zoom: 1 }}
        style={{ position: "absolute", inset: 0 }}
        gl={{ alpha: false, antialias: true }}
      >
        <color attach="background" args={[BG_COLOR]} />
        <ScreenPixelCamera />
        <CurlField />
        <EffectComposer>
          <Bloom
            intensity={1.4}
            luminanceThreshold={0.1}
            luminanceSmoothing={0.6}
            mipmapBlur
          />
        </EffectComposer>
      </Canvas>
      <div className="pointer-events-none absolute left-6 top-6 z-10">
        <p className="mono-caps text-[10px] text-bone/40">{index}</p>
        <p className="font-serif text-2xl text-bone/80">{title}</p>
        <p className="mono-caps mt-2 text-[10px] text-bone/30">{meta}</p>
      </div>
    </section>
  );
}
